### ISSUE TITLE
Can't get this to communicate with opentrack

### ISSUE THREAD

**Issue by samchamper** [thomasgauthier/FreePIE-OSVR#2]
FreePIE is reading all positional tracking data nicely, but I can't convince FreePIE to communicate the data to opentrack - I can only send yaw/pitch/roll. Any ideas on how can I send opentrack a message with all of the positional info?

**Comment by thomasgauthier** [comment]
Maybe try this script : https://github.com/FlyFSX/OSVRfreepie2/blob/master/examples/osvrfreetrack.py

**Comment by samchamper** [comment]
This did the trick beautifully - I see right where I was doing it wrong, too! Thanks for your update!
