### ISSUE TITLE
Freepie is not recieving any input.

### ISSUE THREAD

**Issue by dezpe** [thomasgauthier/FreePIE-OSVR#3]
Hi Thomas,

thanks for your great work!

I am an absolute beginner in OSVR and py scripting and need some help. I have installed OSVR server (OSVR-Runtime-v0.6-1204-g6cc9262-win-64bit) and have it running. Installed Freepie 1.9.629 and your latest OSVR to Freepie plugin. My script is based on one of your examples but Freepie is not getting any values from the rift. Please see the OSVR server log below and also my script attached.

I am using the Oculus CV1 with the latest software. Could this be the issue?

Would appreciate your feedback. Thanks.

dezpe

![dezpe_osvr_freepie_screen](https://cloud.githubusercontent.com/assets/20353487/16682884/09300af6-44fd-11e6-90e9-cdbfac3519d0.jpg)

**Comment by thomasgauthier** [comment]
I've never tried OSVR with anything other than the Hacker Dev Kit, so this might be the problem. Does the OSVR Tracker View show the tracking of your Rift is working? (Download [here](http://access.osvr.com/binary/osvr-tracker-view))

**Comment by thomasgauthier** [comment]
Closing since I've got no news on that and it seems like an issue specific to your setup.
